apiVersion: v1
kind: Secret
metadata:
  labels:
    git-operator.jenkins.io/kind: git-operator
  name: jx-boot-job-env-vars
type: Opaque
{{- if .Values.jxBootJobEnvVarSecrets }}
data:
  {{- range $pkey, $pval := .Values.jxBootJobEnvVarSecrets }}
  {{ $pkey }}: {{ $pval | toString | b64enc }}
  {{- end }}
{{- else }}
data: {}
{{- end -}}
